spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  application:
    name: bx
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.177.141:3306/glmc?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 6aZvnDG!nwI1xxUP
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp



mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.glyxybxhtxt.dataobject
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  tomcat:
    max-http-form-post-size: 80000000
  servlet:
    context-path: /bx
  port: 80

