spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  application:
    name: glyxybxxt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/glmc?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: yibanglmcdb
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp




mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.glyxybxhtxt.dataobject
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  port: 80
  tomcat:
    max-http-form-post-size: 80000000
http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000